### ISSUE TITLE
OpenSky database support

### ISSUE THREAD

**Issue by varnav** [szpajder/dumpvdl2#21]
Today it's impossible to find openly available up to date `basestation.sqb`
At same time OpenSky project keeps it's aircraft database up to date:

https://opensky-network.org/datasets/metadata/

It would be nice if this DB can be used with dumpvdl2

**Comment by varnav** [comment]
Works for me, I'm getting

`AC info: N549CA, CRJ9, SKW`

@olyair11 do you have a script to generate database file from CSV?

**Comment by olyair11** [comment]
I created a script to generate the BaseStation database for dumpvdl2 from the opensky csv file.
Requires sqlite3 cli. If it is not available in your system install the appropriate sqlite-tools-...
from https://www.sqlite.org/download.html

Unzip and copy the two files in a directory.
To create the DB run: $ bs4dumpvdl2.sh

I have one filter only, insert all aircraft that have non empty registration.
Tomasz, please check... and advice.

[bs4dumpvdl2.zip](https://github.com/szpajder/dumpvdl2/files/7071313/bs4dumpvdl2.zip)

**Comment by szpajder** [comment]
Thanks @olyair11! It works nicely.

I may add the script to the `extras` directory in the dumpvdl2 source tree, so that it will be distributed together with the program. Do you agree?

You will be credited of course.

**Comment by olyair11** [comment]
Thanks Tomasz.
I agree of course. I am glad the script is useful for your project.

**Comment by varnav** [comment]
I tried to implement automated builds: https://github.com/varnav/BaseStation.sqb

**Comment by varnav** [comment]
Also it seems that:

`CREATE INDEX IX_ModeS ON Aircraft(ModeS);`

is not needed because earlier:

`CREATE TABLE Aircraft(ModeS PRIMARY KEY, Registration, ICAOTypeCode, OperatorFlagCode, Manufacturer, Type, RegisteredOwners);`

ModeS table is already a primary key.

**Comment by olyair11** [comment]
@szpajder @varnav Updated version

[bs4dumpvdl2.zip](https://github.com/szpajder/dumpvdl2/files/7076514/bs4dumpvdl2.zip)

**Comment by varnav** [comment]
I made another optimization: https://github.com/varnav/BaseStation.sqb/commit/9b5ccb8b8fe1e5b55d402714f3d3de6f7e156ec8

Please test.

**Comment by szpajder** [comment]
Thanks @varnav. I was about to point out that it would be a good idea to remove the indermediate csv file afterwards, but I see it done now.

Given that this project now has its own repo with automated buils, maybe let's keep it separate from dumpvdl2's tree? You could then make changes and improvements at will.

Instead of merging it into dumpvdl2 tree I might add a FAQ entry to the README that points to @varnav's repo. What do you think?

**Comment by varnav** [comment]
If we keep it separate I'd be happy to add you as contributors to my repo.

**Comment by gvanem** [comment]
@varnav Based on your script, I've added this functionality (download + creating a SQlite-database) into my own [dump1090](https://github.com/gvanem/Dump1090.git) program. Done by the `aircraft_CSV_update()` function. But for Windows only since it uses [WinInet](https://learn.microsoft.com/en-us/windows/win32/api/wininet/nf-wininet-internetopena) functions to download from OpenSky. And at the moment it needs an external `unzip.exe` program.

**Comment by olyair11** [comment]
> I created a script to generate the BaseStation database for dumpvdl2 from the opensky csv file. Requires sqlite3 cli. If it is not available in your system install the appropriate sqlite-tools-... from https://www.sqlite.org/download.html
> 
> Unzip and copy the two files in a directory. To create the DB run: $ bs4dumpvdl2.sh
> 
> I have one filter only, insert all aircraft that have non empty registration. Tomasz, please check... and advice.
> 
> [bs4dumpvdl2.zip](https://github.com/szpajder/dumpvdl2/files/7071313/bs4dumpvdl2.zip)

minor... correction

**Comment by szpajder** [comment]
I have added a link to Varnav's repository to dumpvdl2's README.md file in the unstable branch.
