### ISSUE TITLE
Macos 12.6 Monterey: issue (solved) with lib "lacars-2"; Planeplotter alternatives?

### ISSUE THREAD

**Issue by lawendel** [szpajder/dumpvdl2#31]
Hi, thank you for this software! Just wanted to say I managed to compile on an Macbook Air M1 with 12.6 after solving the same make install question reported for dumphfdl. I had already installed libacars on the same machine, and the compiler wasn't apparently able to find it. So I just set LDFLAGS and CPPFLAGS to the correct path. That worked and dumpvdl2 is running flawlessly (as far I can see) with a RTL-SDR dongle. 
Interpreting the messages, however, is far from trivial for me. What could I do to at least visualize their airborne sources on a map, without Planeplotter?

**Comment by szpajder** [comment]
Thank you for the feedback regarding MacOS.

dumpvdl2 does not have a position extractor engine like dumphfdl, because there aren't many position messages in standardized format on VDL2, while on HFDL there is plenty of them. So basically you are on your own. The most straightforward way of extracting individual fields from messages in real time is to use JSON-formatted output over ZMQ sockets. Using that, you may write a script that receives messages from dumpvdl2, extracts coordinates, timestamp and ICAO hex from messages which you are interested in, format the data into a Basestation-compatible format and send the result to an app that can parse and visualise that (Virtual Radar Server, for example). However note that the reception range that you get on VDL2 is probably similar to the ADS-B range from the same location, so if you just want to see aircraft on the map, then setting up an ADS-B reception station is a better idea. You will get much more positional data from ADS-B than from VDL2.

**Comment by lawendel** [comment]
Thanks for these observations. Acarsdec’s Thierry Leconte mentioned Kevin
Elliott’s project, Airframes, which seems to converge toward this idea of
collective sharing/analysis/visualization of scars and vdl2 data. Kevin
repository on GitHub
https://github.com/kevinelliott, gives out lots of applications and food
for thought. Too bad I’m so lagging as a coder!

A.

Il giorno mer 14 set 2022 alle 23:32 Tomasz Lemiech <
***@***.***> ha scritto:
