### ISSUE TITLE
"reserved" destination

### ISSUE THREAD

**Issue by jmhayes-table** [szpajder/dumpvdl2#9]
I got an interesting message today:

`[2019-03-06 13:58:53 UTC] [136.975] [-36.1/-50.7 dBFS] [14.7 dB] [0.5 ppm]
A2B8DB (Aircraft, On ground) -> 5031EA (**reserved**): Command
AVLC type: I sseq: 0 rseq: 0 poll: 0
ACARS (warning: CRC error):
 Reg: .N2748U Flight: UA0872
 Mode: 2 Label: H1 Blk id: 1 Ack: ! Msg no.: D1 A
 Message:
  #DFBACM01ACM304BSN2748U  UAL872  RCTPKSFO060319   9ER125130582883110UALACMAD^M
  118 384084028722873-2993-299434999350005516T, 7911 7842 8#3 83314883^M
  475511111^U3615540000000 48 394410-1343427 1057  57 1114^MJ%-000
`

The "reserved" string comes from an array in avlc.c but there are multiple index entries that resolve to "reserved" ... maybe you could use "reserved0", "reserved2", etc. so that when they come up again we can look further to see what the deal was ...?

**Comment by szpajder** [comment]
The deal was that the message was probably corrupted already at the source :)

I prefer to keep the human readable output format readable and not overly cluttered. It also should not change too often without an important reason, because people have scripts for parsing their logs, so it's no good to make these scripts break every so often.

Right now there is `--raw-frames` option which displays the contents of the AVLC frame in hex, so you can use it to investigate such oddities. In the next release (or so) the behaviour of this option will change - it will dump the whole AVLC frame, including the header, so that addressing fields will be present in the output as well.
